FROM python:3.8

RUN pip install Flask requests uwsgi

COPY app.py /app.py

CMD uwsgi --master \
  --workers $WORKERS \
  --threads $THREADS \
  --protocol http \
  --socket 0.0.0.0:$PORT_APP \
  --module app:app

